# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pricing"
url = "/pricing"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 3

# footer menu left
[[footer_left]]
name = "CI/CD Services"
url = "#"

[[footer_left]]
name = "Cost Optimization"
url = "#"

[[footer_left]]
name = "SRE Consulting"
url = "#"


# footer menu middle
[[footer_middle]]
name = "DevOps Solutions"
url = "#"

[[footer_middle]]
name = "Cloud Migration"
url = "#"

[[footer_middle]]
name = "Monitoring & Alerts"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "/terms-conditions"